### ISSUE TITLE
training parameters

### ISSUE THREAD

**Issue by shuohan** [SmilingWolf/SW-CV-ModelZoo#1]
Hi,

[train_convnext.py](https://github.com/SmilingWolf/SW-CV-ModelZoo/blob/main/train_convnext.py) seems to have different training hyperparameters from your most recent release. I wonder if you could share the scripts that you used to get the model checkpoints [models_db2021_5500_2022_10_21](https://github.com/SmilingWolf/SW-CV-ModelZoo/releases/tag/models_db2021_5500_2022_10_21). Thank you for your help!

**Comment by SmilingWolf** [comment]
- batch_size: 256
- total_epochs: 200
- stochdepth_rate: 0.5
- image_size: 448

Everything else as per the script at time of the release: https://github.com/SmilingWolf/SW-CV-ModelZoo/blob/1d3f947f42132336e4d671c023e13d5788726481/train_convnext.py
