### ISSUE TITLE
[Question] About captioning script.

### ISSUE THREAD

**Issue by a-l-e-x-d-s-9** [SmilingWolf/SW-CV-ModelZoo#4]
Hi @SmilingWolf,

I've been told by 金Goldkoron on ED2 Discord server, that you have some very cool captioning script that allows large batches with WD14 taggers.
Have you published it somewhere, can you please share it?

Thank you!

**Comment by SmilingWolf** [comment]
I kinda wanted to add more features to it before publishing, but never got around it sooo... https://github.com/SmilingWolf/WDMassTagger

I'm assuming 金Goldkoron already explained how it works and its current limitations, but just in case:
- it uses Tensorflow, this means CUDA 10.2 and TF 2.10 if you're on Windows unless you're using WSL2;
- it currently only outputs general tags (no characters/ratings);
- you have to download the TF model files and csv files from the huggingface repo manually, place them wherever you like and point to them with the `--model-folder` and `--tags-csv` cmdline arguments, respectively.

**Comment by a-l-e-x-d-s-9** [comment]
Thank you very much!
